# Generated by Django 3.1.6 on 2021-03-14 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subimage',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='topimage',
        ),
    ]
