# Generated by Django 3.1.6 on 2021-03-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210315_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='メールアドレス'),
        ),
    ]
