# Generated by Django 3.1.6 on 2021-03-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
