# Generated by Django 3.1.6 on 2021-03-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profile_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='campany',
            new_name='company',
        ),
    ]
